name: Trigger auto deployment for kyro-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kyro-container-app-AutoDeployTrigger-1209ff67-3c2f-4518-b573-6452983cffb8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: kyroregistry.azurecr.io
          username: ${{ secrets.KYROCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.KYROCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kyroregistry.azurecr.io/kyro-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KYROCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n kyro-container-app -g kyro-grp --server kyroregistry.azurecr.io --username  ${{ secrets.KYROCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.KYROCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n kyro-container-app -g kyro-grp --image kyroregistry.azurecr.io/kyro-container-app:${{ github.sha }}
